name: ASP.NET Core CI/CD
 
on:
  push:
    branches:
      - master  # Runs pipeline when code is pushed to main branch
  pull_request:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Use .NET 8
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
 
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal
 
    - name: Publish the project
      run: dotnet publish -c Release -o published
 
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: published
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: published-app
        path: published
 
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: "YourAppServiceName"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: "published"
